#Default port is 1002
server:
  port: 1002

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
#  serviceUrl:
#    defaultZone: http://localhost:1001
  
